<?php

return [
  // 'default_category_id' => 476,
  'default_category_id' => null,
  'belok' => [
    'link' => 'https://belok.ua/prices/StlPrice.xml',
    'brands' => [
      "AMIX",
      "BlenderBottle",
      "BPI",
      "Fitness authority",
      "Haya Labs",
      "IronMaxx",
      "Olimp Nutrition",
      "Optimum Nutrition",
      "Quamtrax",
      "Redcon1",
      "Sporter"
    ]
  ],
  'proteinplus' => [
    'link' => 'https://proteinplus.pro/api/xml/f1dd6470-beaf-11e3-a65a-1cc1dec680ca.xml',
    'banned_brands' => [
      "4Life",
      "4yourhealth",
      "7 Nutrition",
      "7Sports",
      "Набори",
      "Activlab",
      "Applied Nutrition",
      "Arm & Hammer",
      "Bad Ass",
      "BLASTEX",
      "Bluebonnet Nutrition",
      "Bounty",
      "BPI sports",
      "California Gold Nutrition",
      "Casno",
      "Cellucor",
      "Child Life",
      "Cobra Labs",
      "Country Life",
      "DNA Supps (OLIMP)",
      "Doctor's BEST",
      "Dr. Mercola",
      "Dymatize",
      "ELITE Labs",
      "Energy Body",
      "Enzymedica",
      "Euroshaker",
      "EVLUTION Nutrition",
      "FitLife",
      "FitMax",
      "Fitness Authority",
      "Force Factor",
      "Fortogen Nutrition",
      "Futurebiotics",
      "Garden Of Life",
      "Gaspari Nutrition",
      "Genius Nutrition",
      "GNC",
      "Grassberg",
      "Healthy Origins",
      "Hydra Cup",
      "IronMaxx",
      "Kevin Levrone",
      "Labrada Nutrition",
      "Mars",
      "Maxler",
      "Maxx",
      "Megabol",
      "MEX Nutrition",
      "Mommy's Bliss",
      "Monster Energy",
      "Multipower",
      "Muscle Pharm",
      "Muscle Pharm Arnold Series",
      "MuscleTech",
      "Natrol",
      "Natural Factors",
      "Nature's Life",
      "NeoCell",
      "NutraBolics",
      "NutraMedix",
      "NutriBiotic",
      "Nyam",
      "Omne Diem",
      "PharmaCare",
      "PipingRock",
      "Pro Supps",
      "ProMera Sports",
      "Quest Nutrition",
      "Rabeko",
      "Rainbow Light",
      "Real Pharm",
      "Redcon1",
      "SAN",
      "Sante",
      "SFD",
      "SIS",
      "Slim",
      "SNICKERS",
      "Spider Bottle",
      "SportFaza",
      "Strong FIT",
      "Super Nutrition",
      "Swanson",
      "Syntrax",
      "Tesla Sports Nutrition",
      "Twinlab",
      "UNS",
      "Wana",
      "Warrior",
      "Weider",
      "Yamamoto nutrition",
      "YumEarth",
      "Zoomad Labs"
    ]
  ],
  'dobavkiua' => [
    'link' => 'https://crm.dobavki.ua/media/export/product/dobavki_opt_price.xml',
    'banned_brands' => [
      "All Be Ukraine",
			"Beaver Professional",
      "A'pieu",
      "Advanced Orthomolecular Research AOR",
      "Amix Nutrition",
      "Arthur Andrew Medical",
      "Artnaturals",
      "Aura Cacia",
      "Bach",
      "Beauty of Joseon",
      "Benton",
      "Blistex",
      "Cantu",
      "CELIMAX",
      "Cos De BAHA",
      "Crystal Star",
      "D'adamo",
      "Daeng Gi Meo Ri",
      "De La Cruz",
      "Deva",
      "DY Nutrition",
      "Dymatize Nutrition",
      "Earth Therapeutics",
      "Earth's Creation",
      "Eucerin",
      "EuroPharma, Terry Naturally",
      "Fifty 50",
      "Flora",
      "Forces of Nature",
      "Gaia Herbs",
      "Gaia Herbs Professional Solutions",
      "GAT",
      "GNC",
      "Godefroy",
      "Grab Green",
      "Harney & Sons",
      "Hearos",
      "Herb Pharm",
      "Herbs Etc.",
      "Heritage Store",
      "Hobe Labs",
      "InstaNatural",
      "Irwin Naturals",
      "Johnson & Johnson",
      "Kiss My Face",
      "Klean Athlete",
      "Kosette",
      "Lunette",
      "MacroLife Naturals",
      "Manyo",
      "Maxim Hygiene Products",
      "Mielle",
      "Mild By Nature",
      "Miyo",
      "MRM Nutrition",
      "Muscle Pharm",
      "Naturally Fresh",
      "NaturVet",
      "Neosporin",
      "Neutrogena",
      "NOSOROG",
      "Odor Eaters",
      "Ojio",
      "PharmaCare",
      "Planetary Herbals",
      "Priorin",
      "Quantum Health",
      "Quiz",
      "Rael",
      "Real Barrier",
      "Reserveage Nutrition",
      "Seagate",
      "SheaMoisture",
      "Similasan",
      "Six Star",
      "Some By Mi",
      "St. Dalfour",
      "Stridex",
      "Sunny Green",
      "Super Nutrition",
      "Superior",
      "Tesla",
      "The Seaweed Bath Co.",
      "The Spice Lab",
      "Traditional Medicinals",
      "Tresemme",
      "TwinLab",
      "Vaseline",
      "Visine",
      "Wet n Wild",
      "Zesty Paws",
    ],
    'brands_overprice_32' => [
			"Solgar",
			"Thorne Research",
			"Neocell", 
			"Metagenics", 
			"Douglas Laboratories"
    ],
    'brands_overprice_50' => [
			"Orthomol",
    ],
    'brands' => [
      "21st Century",
			"Natural Factors",
			"Boiron",
			"California Gold Nutrition",
			"Carmex",
			"ChildLife",
			"Country Life",
			"Doctor's Best",
			"Douglas Laboratories",
			"Earth`s Creation",
			"Eucerin",
			"Fairhaven Health",
			"Gerber",
			"Healthy Origins",
			"Irwin Naturals",
			"Jarrow Formulas",
			"KAL",
			"Klaire Labs",
			"Lake Avenue Nutrition",
			"Life Extension",
			"Life-flo",
			"Metagenics", 
			"Mommy's Bliss",
			"NatraBio",
			"Natrol",
			"Naturade",
			"Nature's Plus",
			"Nature's Way",
			"Neocell",
			"Nordic Naturals",
			"Now Foods",
			"NutriBiotic",
			"Nutricology",
			"Orthomol Natal",
			"Osteo Bi-Flex",
			"Pure Encapsulations",
			"Puritan's Pride",
			"Solaray",
			"Solgar",
			"Source Naturals",
			"Swanson",
			"Thorne Research",
			"Vitables",
			"YumEarth",
			"Zand",
    ]
  ]
];